### ISSUE TITLE
REST API host in docs doesn't work

### ISSUE THREAD

**Issue by TimDaub** [snapshot-labs/snapshot-hub#105]
see 

- https://github.com/snapshot-labs/snapshot-docs/blob/master/guides/archived/hub-api.md
- https://docs.snapshot.org/guides/archived/hub-api

but when I follow a link, e.g. https://hub.snapshot.page/api/spaces

That page seems to be down. In fact, all of https://hub.snapshot.page seems to be down.

**Comment by ChaituVR** [comment]
Hello @TimDaub Please use the new GraphQL API https://docs.snapshot.org/graphql-api
above docs links are archived links and many of those APIs are deprecated, Thanks
