### ISSUE TITLE
Allow max 32 proposals per day per space

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#165]
And max 320 proposals per month

**Comment by RickVM** [comment]
Why, and is there any way to upscale these limits?

**Comment by bonustrack** [comment]
@RickVM Can you tell more about your use case? What's your need to have more than 32 proposal per day?

**Comment by densmirnov** [comment]
> @RickVM Can you tell more about your use case? What's your need to have more than 32 proposals per day?

For example, when you are using snapshot for other activities. For example, I am using it as part of the final test for students, where they have to create a proposal as part of the challenge.
