### ISSUE TITLE
Don't store duplicate vote

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#170]
When someone voting multiple time we store all the votes, instead we should update latest vote and make sure we have only latest vote cast for an address

**Comment by ChaituVR** [comment]
@bonustrack what should happen to the record in the `messages` table. we can ignore it? or should delete it?

**Comment by mktcode** [comment]
We could add a unique key constraint after removing the duplicates. Something like this:

```
ALTER TABLE `votes` ADD UNIQUE `unique_vote`(`voter`, `proposal`);
```

**Comment by bonustrack** [comment]
@ChaituVR We can ignore it
@mktcode Yes exactly
