### ISSUE TITLE
Support with Count or Sum Total Functions

### ISSUE THREAD

**Issue by howardpen9** [snapshot-labs/snapshot-hub#216]
### Expected behavior
for example, in BitQuery
https://graphql.bitquery.io/ide/kB1xFizycB/qHRgRPz4gD

### Actual behavior
Right now, I can't get distinct users amount in a specific proposal. Or the amount of specific token participate in one proposal.

**Comment by zzuziak** [comment]
Closing this one as it will be handled as a part of #199
