### ISSUE TITLE
Fixing reliability issues with scores in the GraphQL API

### ISSUE THREAD

**Issue by jasperverbeet** [snapshot-labs/snapshot-hub#218]
## Behavior

Currently, aside from storing voting data on IPFS, this data is also retained in a centralized database. This is useful to the developer, because now the GraphQL API can include voting power without relying on the availability of the _Scores API_, which stability is often limited by the blockchain provider. However, the data the GraphQL API returns doesn't correspond with the results of the _Scores API_.

## Explanation

The current implementation of the GraphQL API is limited because the scores are only calculated correctly if the proposal state is `closed`. That means that the data the API returns is not reliable unless the proposal has been expired (and all votes are counted).

When looking at the following lines the scores are only updated when the scores state is `final` (which depends on the proposal state to be `closed`).

https://github.com/snapshot-labs/snapshot-hub/blob/8b70ce4b6f8e43df65eaba8758e9366af798ffe5/src/scores/index.ts#L90-L119

Further more, looking at the following code we can see that the `getProposalScores()` is called on the `proposal/end` event, further indicating the scores are not reliable up to that point.

https://github.com/snapshot-labs/snapshot-hub/blob/8b70ce4b6f8e43df65eaba8758e9366af798ffe5/src/events/index.ts#L78-L90

There is also this recursive method, that updates the scores for a proposal after its created (if you're lucky), which we should probably get rid of or do a better implementation.

https://github.com/snapshot-labs/snapshot-hub/blob/8b70ce4b6f8e43df65eaba8758e9366af798ffe5/src/scores/index.ts#L162-L174

## Solution

The best way I see to resolve the reliability issues is to create a `proposal/voted` event that the event handler can use to recalculate the scores. Together, with the `scores_state` and `scores_updated` attributes this should give the develop enough data to show the current polls before they are made final.

We should probably also think about _retrying after error_ behavior in the custom built event handler, but that is relevant for all events. Furthermore, I think this behavior should be better documented.

**Comment by ChaituVR** [comment]
GraphQL API should return reliable data as score API now.
