### ISSUE TITLE
Bug: too many requests error blocking snapshot.org render

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#221]
For some reason I got this error while I'm sure I send way less than 32 requests for 12 sec, something is wrong is rate limit helper
![image](https://user-images.githubusercontent.com/16245250/147293756-47492099-49bf-4993-80aa-7b80cbf41055.png)

**Comment by stormsson** [comment]
@bonustrack tried to replicate online at address
https://snapshot.org/#/olympusdao.eth/proposal/0x71129f3282c2632eda8e43c321581065e1897a06b0e29d83153014ba9b229445  

I'm not encountering the error

**Comment by ChaituVR** [comment]
Yea I can't reproduce too. this could be something that occurs very rarely or maybe only on Heroku in production
