### ISSUE TITLE
Return an error when user pass different strategies than space's strategies

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot-hub#235]
While creating a proposal, right now if we pass different strategies to the hub, we enforce the same strategies as space, but IPFS still has the strategies that the user signs and it is confusing, we should return an error if different strategies are passed

Update: Now we store the same strategies as space but signed message may contain original strategies than space strategies

**Comment by zzuziak** [comment]
Hey @bonustrack, @ChaituVR what's the status here? Something we could handle in a cooldown?

**Comment by ChaituVR** [comment]
We are not passing strategies into IPFS anymore. (while creating a proposal) so I think we can close this
