### ISSUE TITLE
Add total number of proposals in a space to space query

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot-hub#238]

**Comment by bonustrack** [comment]
This is already in place

**Comment by hjjlxm** [comment]
we can make this figure a show in the space, just like spaces num in the homepage. @bonustrack 
![spaces# in homepage](https://user-images.githubusercontent.com/31681895/163548648-e9948a9b-8a0a-420d-b47b-1efa1c7a66e7.png)

**Comment by samuveth** [comment]
@bonustrack what is the query for this?
