### ISSUE TITLE
Vote.settings is undefined when being passed to formatSpace

### ISSUE THREAD

**Issue by midgerate** [snapshot-labs/snapshot-hub#270]
We are currently passing undefind to settings in the formatSpace inside formatVote method. 

As you can see here, vote in the query does not have space settings via a join. 
https://github.com/snapshot-labs/snapshot-hub/blob/85ab54768110c525bd0b308c92eeaf0195ebac32/src/graphql/operations/votes.ts#L43-L53

and inside format vote we pass vote.settings which will be undefined. 
https://github.com/snapshot-labs/snapshot-hub/blob/85ab54768110c525bd0b308c92eeaf0195ebac32/src/graphql/helpers.ts#L49
 
We need to check if this is even needed.

**Comment by mktcode** [comment]
Maybe worth mentioning what you told me. Settings where removed in this query to hot-fix a performance issue. So just adding it back probably won't help a lot.

**Comment by zzuziak** [comment]
@ChaituVR could you have a look if still valid or shall we close?
