### ISSUE TITLE
Move events to a separate webhook server

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#273]
Currently with the webhook service we are storing events on the db and send them to all subscribers. We should do this on another server to keep the hub a light as possible. The server for snapshot-discord would be ideal for this, we could rename it to snapshot-webhook, there is already a db with MySQL, we can use it to store events and remove it from snapshot-hub. 

It would work like this:
- When someone create a proposal, the hub send a request to snapshot-webhook with an event `proposal/created`.
- Then snapshot-webhook store the events on the db for proposal/start, /end, /created like this https://github.com/snapshot-labs/snapshot-hub/blob/master/src/writer/proposal.ts#L147-L168 
- Then we run a function at regular interval to check if there is new events and send them to all subscribers like this https://github.com/snapshot-labs/snapshot-hub/blob/master/src/events/index.ts#L114

On the hub we can then remove the table "events", we will still need the `proposal/end` event to calculate results on ended proposal but for this we can simply run a function at regular interval to check proposals expired without score status. For `proposal/deleted` we would simply send a request to snapshot-webhook when someone delete a proposal and the webhook would relay that.

**Comment by midgerate** [comment]
I will take this

**Comment by ChaituVR** [comment]
Plan for migration:

- [ ]  Deploy new changes to snapshot-discord, make sure old code is still working (PR - soon)
- [ ]  Deploy changes on snapshot-hub to call snapshot-discord on new events, old events still run on snapshot-hub (PR - soon)
- [ ]  Migrate events table (old events) and append to the snapshot-discord table 
- [ ]  Remove events code from snapshot-hub (PR - soon)
- [ ]  Final changes on both repositories and cleanup (PRs - soon)
