### ISSUE TITLE
[GraphQL]  Filter votes by choice

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot-hub#290]
Currently there is no way to filter votes by choice. There should be a where-filter taking an array of choices to return.

**Comment by hjjlxm** [comment]
agreed:) put “choice” to the schema has meant a sense

**Comment by samuveth** [comment]
> Currently there is no way to filter votes by choice. There should be a where-filter taking an array of choices to return.

Add search vote by address while your up to it 😄

**Comment by bonustrack** [comment]
Closing this for now as there isn't any elegant solution for it, and it's unlikely we will get one anytime soon.
