### ISSUE TITLE
Unable to publish a proposal

### ISSUE THREAD

**Issue by WUXINYIMiffy** [snapshot-labs/snapshot-hub#294]
### Expected behavior
publish proposal

### Actual behavior
failed to publish a proposal with an error ' Oops, wrong proposal format'
![截屏2022-04-08 下午7 23 32](https://user-images.githubusercontent.com/78845734/162553067-dcc6fb76-d0cb-4ce4-a4b0-9f231749444f.png)

### Steps to reproduce the behavior
create a simple proposal then click on publish, sign on metamask, meet error

**Comment by samuveth** [comment]
@WUXINYIMiffy thanks for reporting this. For the future when it's something more urgent like this it would be better to ping us on discord.

**Comment by WUXINYIMiffy** [comment]
> 

Copy that. Thanks!
