### ISSUE TITLE
Store only latest vote per user on the same proposal

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#299]
On Snapshot you can vote multiple time on a same proposal and only your latest vote count. On the hub we store all the votes on the db even if someone voted multiple time on the same proposal. 

When we query for votes on the db we apply a condition to only retreive latest vote per unique voter, doing this query is intensive: 
https://github.com/snapshot-labs/snapshot-hub/blob/master/src/graphql/operations/votes.ts#L45-48

There is also too little benefit to keep the previous votes. We should instead only keep on the db the latest vote per user and enforce it with the mysql schema, this would make the query much simpler and make it scale better. 

The tricky part is that we should make sure we keep the vote with the highest timestamp, the hub could receive a first vote with a timestamp of 10 and a second vote with a timestamp of 9, in this case we should keep only the first vote. In the case if the timestamp are same we need a deterministic way of saying which one should we use and for this I suggest to use localCompare with the id of the vote.

**Comment by mktcode** [comment]
When this came up some time ago, I also had the idea of some sort of "handshake" where the hub and the client "agree" on a timestamp beforehand. One downside would be an additional request and there was something else problematic with this but I don't remember. So at least for the record, this was what I had in mind.

![image](https://user-images.githubusercontent.com/6792578/163566494-eec8475c-2d0c-4f80-841a-7b148b06a1e4.png)

Would replace this logic then:
https://github.com/snapshot-labs/snapshot-hub/blob/4bff607b7cbbb8f59ae0a547f897e0657bf5964a/src/ingestor/typedData/index.ts#L22-L33

**Comment by bonustrack** [comment]
@mktcode I'm not sure to understand how it help?

**Comment by mktcode** [comment]
We talked about this yesterday but just for the record: This was just more a generalized idea to make the hub be in charge of setting message timestamps (and potentially other data) while still allowing the user to sign them.
