### ISSUE TITLE
Adding Score to IPFS Data

### ISSUE THREAD

**Issue by dmosites** [snapshot-labs/snapshot-hub#34]
AirSwap is working on a way for governance participants to claim earnings based on voting weight. To achieve this without adding trusted process or infrastructure, voter (author) address and weight (score) would be included in each certified vote and be subsequently verifiable by a smart contract.

Given that the relayer certifies each vote, author and score could be included in the message that is signed by the relayer when each vote is submitted. The relayer is doing this work [here](https://github.com/balancer-labs/snapshot-hub/blob/master/server/index.ts#L196).

```
const relayerSig = await relayer.signMessage(authorIpfsRes);
const relayerIpfsRes = await pinJson(`snapshot/${relayerSig}`, {
  address: relayer.address,
  msg: authorIpfsRes,
  sig: relayerSig,
  version: '2'
});
```

To determine score, the `snapshot.js` module has a `getScores` function.

```
const scores: any = await getScores(
  space.key,
  space.strategies,
  space.network,
  getProvider(space.network),
  Object.values(proposals).map((proposal: any) => proposal.address)
);
```

The relayer could then include the author and score in the message it signs.

```
const message = JSON.stringify({ author, score, ipfsHash: authorIpfsRes });
const relayerSig = await relayer.signMessage(message);
const relayerIpfsRes = await pinJson(`snapshot/${relayerSig}`, {
  address: relayer.address,
  msg: message,
  sig: relayerSig,
  version: '2'
});
```

The contract verification function would either take `msg` as an argument and parse the author and score out of it...

```
function verify(bytes memory msg, bytes memory sig) public {}
```

or take `author` and `score` as arguments and reconstruct the `msg` JSON string prior to verifying it.

```
function verify(address author, uint256 score, bytes ipfsHash, bytes memory signature) public {}
```

Alternatively, if score is included in the author signed message, then both the author and relayer signatures could be submitted to the contract. In this case, the contract would need to parse the author and score out of the author message, and then generate the CID of the author data to ensure it matches the authorIpfsRes found in the relayerIpfsRes message.

These are just initial thoughts but really appreciate you guys taking a look. Thanks 🙌

**Comment by bonustrack** [comment]
Closing this issue for now, this was discussed previously that score may change when using snapshot in future thus making storing voting power not relevant here
