### ISSUE TITLE
schema.sql in readme.md 404s

### ISSUE THREAD

**Issue by i001962** [snapshot-labs/snapshot-hub#351]
### Expected behavior
Clicking link in readme should 200
### Actual behavior
Clicking link in readme 404s
### Steps to reproduce the behavior
Load this https://github.com/snapshot-labs/snapshot-hub
then click this https://github.com/snapshot-labs/snapshot-hub/blob/master/src/helpers/database/schema.sql
404s

**Comment by mktcode** [comment]
👍🏻
