### ISSUE TITLE
Run snapshot hub locally 

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [snapshot-labs/snapshot-hub#40]
### Actual behavior
I got the following error when trying to run hub service 

![image](https://user-images.githubusercontent.com/5875315/108664173-0d735000-7487-11eb-9250-3dfa8424a083.png)

### Steps to reproduce the behavior
1. git clone the repo
2. yarn install
3. yarn start

**Comment by Xuefeng-Zhu** [comment]
After install cross-fetch manually, I got another error

![image](https://user-images.githubusercontent.com/5875315/108664595-ed905c00-7487-11eb-92ec-997b3ce65c6b.png)

**Comment by bonustrack** [comment]
This repo use npm, not yarn, can you try with it?

**Comment by Xuefeng-Zhu** [comment]
@bonustrack Thank you for the quick response. I tried npm, but got the same error

**Comment by ChaituVR** [comment]
@Xuefeng-Zhu  Make sure to update the .env file :)

**Comment by Xuefeng-Zhu** [comment]
@ChaituVR Cool. thanks

**Comment by ChaituVR** [comment]
@Xuefeng-Zhu  we will try to update the README file soon
