### ISSUE TITLE
Use "messages" ops to query new event on snapshot-webhook

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#437]
Instead of sending callback to snapshot-webhook server we could just query for messages sorted by `mci` and trigger event based on that.

**Comment by bonustrack** [comment]
We could use query like this:
https://hub.snapshot.org/graphql?query=query%20%7B%0A%20%20messages(%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20type_in%3A%20%5B%22proposal%22%2C%20%22delete-proposal%22%5D%0A%20%20%20%20%20%20mci_gt%3A%207928520%0A%20%20%20%20%7D%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20mci%0A%20%20%20%20type%0A%20%20%7D%0A%7D%0A

**Comment by ChaituVR** [comment]
To make sure we are not sending duplicate 
Steps:
1. While sending data to webhook, include `mci` in the payload
2. On webhook, store `mci` and `created` in the events table
3. Fetch data from messages based on latest `mci` stored

**Comment by ChaituVR** [comment]
The above process is a bit complicated, new steps:
1. Add a new table `mci` with the last event stored in DB (Find out `mci` of the last event received from the hub and update the table)
```sql
CREATE TABLE mci (
  last_index INT NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```
2. Get `mci` stored in DB and run the events query (make sure to run it only if there is a valid `mci` stored )
3. Write an events query to fetch events time to time based on `mci` like suggested by Fabien with the latest `mci` (Make sure to store only unique events)
4. Update `events` table and `mci` table
