### ISSUE TITLE
Add support for API key

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#438]
We should introduce API key to help monitor number of request that the API receive and prevent someone to spam the hub.

**Comment by zzuziak** [comment]
Pitch details [here](https://www.notion.so/snapshotlabs/API-Keys-bfd70d80bb004c21b52c07819b33fdf1) 🙏

**Comment by zzuziak** [comment]
Closing as the there is another API Keys issue active in #541
