### ISSUE TITLE
Vote query on GraphQL is not working

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot-hub#444]
Reported by @hjjlxm on discord

https://hub.snapshot.org/graphql?operationName=Vote&query=query%20Vote%20%7B%0A%20%20vote%20(%0A%20%20%20%20id%3A%20%220x5e2bbca461950efae33244fbf7707b8f907780d7521f331227956692adff9862%22%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20voter%0A%20%20%20%20created%0A%20%20%20%20proposal%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20choice%0A%20%20%20%20space%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

Irrespective of what we give as input `id` it always fail with error:
```json
{
  "errors": [
    {
      "message": "Unexpected error value: \"request failed\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "vote"
      ]
    }
  ],
  "data": {
    "vote": null
  }
}
```

**Comment by ChaituVR** [comment]
Also should be possible to find a vote with IPFS instead of just id (UI just display IPFS)

**Comment by hjjlxm** [comment]
> Also should be possible to find a vote with IPFS instead of just id (UI just display IPFS)

Thanks for raising this. Vote id is more abstract and cannot be accessed through Receipt (only ipfs id). Therefore, using ipfs id instead as a condition for vote query is more intuitive

**Comment by ChaituVR** [comment]
Update: can't reproduce this in my local, issue must be with production DB, 

Error:
```
sqlMessage: \"Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='\",
```

**Comment by wa0x6e** [comment]
I can confirm that this is a DB issue, by running the underlying Mysql query directly on the db give the same error.

**Comment by wa0x6e** [comment]
Running the following SQL command 

```
SELECT TABLE_SCHEMA 
    , TABLE_NAME 
    , COLUMN_NAME 
    , COLLATION_NAME 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_schema = 'defaultdb';
```

We can see that the `votes` table is not using the same collation as all the other tables.

`votes` is using `utf8mb4_0900_ai_ci`, whereas the rest of the tables are using `utf8mb4_unicode_ci`

This is the reason there is a `Illegal mix of collations` error. On some queries, SQL is able to coerce different collation transparently, but in case it's not able to, this error will continue to happens.

Furthermore, from 

```
SELECT @@character_set_database, @@collation_database; 
```

it seems the database default collation is `utf8mb4_0900_ai_ci`, so all future tables will be created with an incompatible collation with the existing tables.

The recommended solution will be to:
- choose a unique collation to use for all tables
- change the default database collation to the chosen collation
- update all table not using the chosen collation to the chosen collation

With more than 12 millions rows in the `votes` table, an `ALTER TABLE` query will be expensive, and will freeze the database during the query execution, which may takes time.
Another alternative to `ALTER` may be needed.

A dirty quick fix will be to coerce the columns ourselves in the SQL query, but this will disable the index usage
