### ISSUE TITLE
[BUG] Votes count is zero with shutter

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot-hub#523]
### Expected behavior
The votes count should show the number of votes regardless of the voting type and privacy settings.

### Actual behavior
Example proposal `pistachiodao.eth/proposal/0xa5077ef17097b1d59304b110337bd1c7ce98d95d3ff81d138c3886a80074b4d9`
The hub is returning zero for `props.proposal.votes` 

Example screenshot of missing votes count 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/51686767/205027467-5384aa63-07f7-4418-8050-d3079c01f73c.png">

**Comment by samuveth** [comment]
@bonustrack can we get someone on this?

**Comment by ChaituVR** [comment]
In this case, we should also warn that the vote count may reduce in the future right? (if someone vote with invalid choices)

**Comment by ChaituVR** [comment]
If someone is using graphQL API, it will still be confusing with quorum and votes count. we may have to add new fields to suggest they are not final, maybe like `votes_state` and `quorum state` similar to `scores_state`

Any thoughts @bonustrack ?

**Comment by samuveth** [comment]
@ChaituVR, no the votes count will not reduce if some votes are invalid. We show invalid votes in the list of votes, but with a ⚠️ icon and a tooltip where the choice is.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/51686767/222951378-835ad199-558b-4d00-96c0-6c9432dbe418.png">

**Comment by ChaituVR** [comment]
Completed in https://github.com/snapshot-labs/snapshot-sequencer/pull/23
