### ISSUE TITLE
Setup backups of the db on different provider

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#524]
We should regular backups the data from our db in a different provider, not just DO.

**Comment by zzuziak** [comment]
Hi @bonustrack, do you have any specific solution in mind? Happy to turn it into a small DevOps pitch 🙏

**Comment by wa0x6e** [comment]
Per my understanding, this is done, and can be closed

**Comment by bonustrack** [comment]
Yes this was solved with simplebackups
