### ISSUE TITLE
Implement API Keys 

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/snapshot-hub#541]
## Background

Currently Snapshot’s API is available for anyone to access. It creates several issues, the main issue being that it can lead to server overload as users make humongous requests to the API without any limits. Recently it led to a serious downtime on Friday, Dec 9th, when one of the users initiated a massive API call that brought it down.

More details in the [project pitch](https://www.notion.so/snapshotlabs/API-Keys-bfd70d80bb004c21b52c07819b33fdf1) on Notion.

## Solution
Implementation of API keys to control the usage of our data.

**Comment by wa0x6e** [comment]
@ChaituVR I think this is completed ?

**Comment by ChaituVR** [comment]
Yeps
