### ISSUE TITLE
Return total voting power on shutter proposals

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot-hub#554]
For ongoing proposals that have shutter enabled, we need to provide the total voting power. This will allow us to display the quorum on the UI along with a warning that the quorum may be inaccurate until the proposal is closed and choices are validated.

**Comment by samuveth** [comment]
@bonustrack can we get someone on this?

**Comment by ChaituVR** [comment]
Completed in https://github.com/snapshot-labs/snapshot-sequencer/pull/23
