### ISSUE TITLE
Fetching >5000 votes for a proposal

### ISSUE THREAD

**Issue by gsgalloway** [snapshot-labs/snapshot-hub#570]
I'm looking for a way to fetch the list of all votes for a proposal when the number of votes for that proposal exceeds 5000. There's a limit in place on the `skip` argument [here](https://github.com/snapshot-labs/snapshot-hub/blob/f7809b04a6f9131f0ba83f02a027462e313b58ff/src/graphql/helpers.ts#L13) that makes this difficult. An example of one such proposal is [0xd810c4cf2f09737a6f833f1ec51eaa5504cbc0afeeb883a21a7e1c91c8a597e4](https://snapshot.org/#/ens.eth/proposal/0xd810c4cf2f09737a6f833f1ec51eaa5504cbc0afeeb883a21a7e1c91c8a597e4).

A halfway workaround is to fetch the first 5000 in ASC order and then another 5000 in DESC order, but this of course does not work for proposals that exceed 10,000 votes, and it requires deduping the results.

Is it possible to remove this limit on the `skip` argument? Imposing limits on page size (`first` argument) and on number of queries is perfectly reasonable, but limiting how far a client can paginate through an already-sorted DB query is a bit surprising.

Alternatively, is there another workaround here?

**Comment by wa0x6e** [comment]
Refer to https://discord.com/channels/707079246388133940/1061540232769577061

The trick is to use an additional filter, `created_gte`
