### ISSUE TITLE
Reduce ranking for spaces with ticket strategy 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot-hub#584]
Spaces with ticket strategy are spamming proposals and votes to reach `#1` on the homepage. We should reduce the ranking of such spaces similar to what we do for testnet spaces.

Discussion:
https://discord.com/channels/955773041898573854/1031838696846131200/1108174043506540544

**Comment by ChaituVR** [comment]
https://github.com/snapshot-labs/snapshot-hub/pull/585
