### ISSUE TITLE
feat: add new api endpoint to check for deleted spaces

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/snapshot-hub#796]
## Goal

Add a new POST `/api/delete-spaces` endpoint, which accept a list of ENS names `['a.eth', 'b.eth']`, and return a JSON list of deleted spaces like `['a.eth']`, or just `[]` if none of the input are deleted spaces

This additional endpoint will avoid having to burden the graphql queries, which does not handle deleted spaces by default.

## Why 

UI does not have a way to check for deleted spaces.
Having that list will allow UI to show filter deleted spaces from the 'Create space' form, and avoid having user completing all the space creation steps, until to get the error "Space deleted, please contact admin" at the end of creation process.

This will lighten the support, which is today getting at least one ticket per week about this error.

See https://github.com/snapshot-labs/snapshot/issues/4516 for UI proposed implementation

**Comment by wa0x6e** [comment]
@ChaituVR and @bonustrack , what do you think ?

**Comment by ChaituVR** [comment]
Sounds good to me
